Testcase
Klan300/league_of_saras pull request #19
Opened 2019-12-07 03:16 UTC by EJEunjiyaz

2019-12-08 10:42 UTC, Klan300 approved these changes

2019-12-08 10:42 UTC, Parkkung approved these changes

2019-12-08 10:44 UTC, kornkritpawit approved these changes
approve

2019-12-08 10:49 UTC, Parkkung requested changes
have a error in test, please fix it

2019-12-08 11:13 UTC, Parkkung approved these changes
everything is ok now

2019-12-08 11:54 UTC, Klan300 requested changes
please look on travis ci and find problem before 12/12/19

2019-12-09 17:58 UTC, EJEunjiyaz commented
> please look on travis ci and find problem before 12/12/19

Thank you. The bug fixed on 10/12/19. Final check, please

2019-12-10 06:41 UTC, Klan300 requested changes

2019-12-10 06:41 UTC, Klan300 commented on Cardgame/tests.py
> +
pls test method number of card of deck models

2019-12-10 06:41 UTC, Klan300 commented on Cardgame/tests.py
> +
test __str__ method of card models too

2019-12-14 15:03 UTC, Klan300 approved these changes

2019-12-14 15:03 UTC, merged