Setting page
Klan300/league_of_saras pull request #3
Opened 2019-11-02 10:13 UTC by EJEunjiyaz

I completely build the setting page with css, add `views` and `urls` in django. Please final check for setting.html and setting.css file.

2019-11-02 10:25 UTC, kornkritpawit commented
Overall is good.

2019-11-03 12:14 UTC, Klan300 commented
- [ ]  can you fix setting to a block on div '.box' 
- [ ]  add link font that I require to setting.html 
`<link href="https://fonts.googleapis.com/css?family=Varela+Round&display=swap" rel="stylesheet">`
- [ ] add css font to setting.css
`* {
font-family: 'Varela Round', sans-serif;
}`

- [ ] don't use `<br>` pls use padding or margin to create space

- [ ] pls put `<script>` below `<body>`

- [ ] pls put `<meta>` `<link>` `<title>` into `<head>` tags

> it have another way to create div box by not using table just kind link `display : flex`  on css
> please read and try this to your code "[flexbox](https://internetingishard.com/html-and-css/flexbox/)"

ขอโทษที่ให้แก้เยอะ แต่เพื่อความเป็นระเบียบของงานแล้วก็ เวลาแต่งจะได้ง่ายแล้วก็สวยมากขึ้น สียังไม่ลงตัวค่อยเพิ่มได้ ถ้ามึงทำได้ มึงจะทำได้อีกเยอะ

2019-11-04 04:37 UTC, Parkkung commented
not necessary to use <br>

2019-11-14 14:26 UTC, EJEunjiyaz commented
I already add flexbox and padding. Please check again.
Thank you

2019-11-16 08:06 UTC, Klan300 commented
<img width="1261" alt="Screen Shot 2562-11-16 at 15 03 18" src="https://user-images.githubusercontent.com/44374820/68990161-54d16080-0882-11ea-931a-1b53ea4736a7.png">
I think It too much big more than it should be. it should have space between time and sound on-off.

2019-11-16 08:13 UTC, Klan300 requested changes
please fix some design on your settings page.

2019-11-18 09:37 UTC, EJEunjiyaz reviewed
Finish

2019-11-18 09:38 UTC, EJEunjiyaz commented
![image](https://user-images.githubusercontent.com/48819898/69041323-e75c3600-0a21-11ea-84ad-913d8d52941a.png)

2019-11-18 09:39 UTC, EJEunjiyaz commented
Please check again @Klan300 . Thank you for always good reviews.

2019-11-18 15:10 UTC, Klan300 approved these changes

2019-11-18 15:21 UTC, Parkkung approved these changes

2019-11-20 04:15 UTC, merged

2019-11-21 09:15 UTC, EJEunjiyaz reviewed
Should fix these format first

2019-11-21 09:15 UTC, EJEunjiyaz commented on Cardgame/static/css/setting.css
> +    content: "";
Remove This